package org.cucumbergrid.junit.runtime.common;

public enum MessageID {
    DISCOVERY,

    REQUEST_FEATURE,
    EXECUTE_FEATURE,
    NO_MORE_FEATURES,
    UNKNOWN_FEATURE,

    TEST_STARTED,
    TEST_FINISHED,
    TEST_RUN_STARTED,
    TEST_RUN_FINISHED,
    TEST_IGNORED,
    TEST_FAILURE,
    TEST_ASSUMPTION_FAILURE,

    RESULTS,
    FORMAT,
    SHUTDOWN,
    NODE_INFO,
}
